name: Deploy to Internet Computer (Simple)

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install DFX
      run: |
        sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Setup DFX
      run: |
        # Use default identity
        dfx identity use default
        
        # Get the principal
        PRINCIPAL=$(dfx identity get-principal)
        echo "Using principal: $PRINCIPAL"
        
    - name: Deploy to IC
      env:
        DFX_NETWORK: ic
      run: |
        # Deploy to IC
        dfx deploy --network ic --yes
        
    - name: Get canister info
      run: |
        dfx canister --network ic info game-studio
        
    - name: Upload deployment info
      uses: actions/upload-artifact@v4
      with:
        name: deployment-info
        path: .dfx/ic/canister_ids.json 